### Package manager ###

# Not much to be done here, the distinction between desktop and server doesn't make sense for a mac, and we already install what we need in "packages.yml"

### Keyboard layouts ###

# TODO : install querty-lafayette here

### Fonts ###

# Recommended fonts for powerlevel10k
# NB : Those will get downloaded but never updated if the source changes. Fine, I guess ?
- name: Download MelsoLGS fonts
  get_url:
    dest: "{{ ansible_user_dir }}/Library/Fonts/{{ item.filename}}"
    url: "{{ item.url }}"
  loop:
    - { filename: "MesloLGS NF Regular.ttf",      url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"}
    - { filename: "MesloLGS NF Bold.ttf",         url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"}
    - { filename: "MesloLGS NF Italic.ttf",       url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"}
    - { filename: "MesloLGS NF Bold Italic.ttf",  url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"}


### Alacritty ###

- name: Load alacritty config via .config/alacritty.yml
  file:
    state:  link
    follow: false
    src:    "{{ remote_directory }}/files/alacritty.yml"
    dest:   "{{ ansible_user_dir }}/.config/alacritty.yml"

### Graphical environment Themes ###

# N/A to Mac

### sway ###

# TODO : find some tiling window manager and set it up
