### Package manager ###

# NB : since the desktop/server distinction doesn't make sense for a mac, we install all packages here, and none in packages.yml
# TODO : Install brew itself
- name: Install usual tools (Darwin)
  homebrew:
    name:
      # NB : alacritty homebrew install is currently unsigned and x86
      # The upstream releases should eventually become a universal binary (waiting for rust 1.49)
      # In the meantime, we install rust with with brew, and then build it ourselves, it gives an arm build
      # cf https://github.com/alacritty/alacritty/pull/4683
      #
      # Build instructions :
      # * git clone https://github.com/alacritty/alacritty.git
      # * cd alacritty
      # * make app
      # * cp -r target/release/osx/Alacritty.app /Applications/
      # * start alacritty with the right-click open on Finder and accept to add a security exception
      #
      # - alacritty
      - rust # to manually build alacritty

      - md5sha1sum # for command md5sum
      - exa
      - prettyping

      - koekeishiya/formulae/yabai # tiling window manager
    state: present

### Keyboard layouts ###

# TODO : install querty-lafayette here

### Alacritty ###

- name: Load alacritty config via .config/alacritty.yml
  file:
    state:  link
    follow: false
    src:    "{{ remote_directory }}/files/alacritty.yml"
    dest:   "{{ ansible_user_dir }}/.config/alacritty.yml"

### Graphical environment Themes ###

# N/A to Mac

### yabai ###

# NB : we're not setting up the scripting addition because :
# * it requires disabling SIP, which is not advisable security-wise
# * it doesn't support M1 Macs anyway

