### Package manager ###

# NB : since the desktop/server distinction doesn't make sense for a mac, we install all packages here, and none in packages.yml
# TODO : Install brew itself
- name: Install desktop packages (Darwin)
  homebrew:
    name:
      - alacritty   # GPU-powered terminal emulator

      - md5sha1sum  # for command md5sum
      - exa
      - prettyping

      # NB : those need to be enabled manually with :
      # * brew services start yabai
      # * brew services start skhd
      - koekeishiya/formulae/yabai  # tiling window manager
      - koekeishiya/formulae/skhd   # hotkey daemon
      # NB : install currently doesn't work
      # NB : cf https://karabiner-elements.pqrs.org/docs/getting-started/installation/ for initial setup
      # TODO : skhd and karabiner are redundant. Make a choice
      # - karabiner-elements          # keyboard customization
    state: present

### Keyboard layouts ###

- name: Create custom fonts directory
  file:
    state:  directory
    path:   "{{ ansible_user_dir }}/Library/Keyboard Layouts"

# NB : this makes the layout available, you still have to select it in options
- name: Download qwerty-lafayette
  get_url:
    dest:     "{{ ansible_user_dir }}/Library/Keyboard Layouts/"
    url:      https://qwerty-lafayette.org/releases/lafayette_macosx_v0.6.keylayout
    checksum: "sha1:a0492cd50b8118a304a462de067825f40a689c28"
    mode:     "0644"

### Alacritty ###

- name: Load alacritty config via .config/alacritty.yml
  file:
    state:  link
    follow: false
    src:    "{{ remote_directory }}/files/alacritty.yml"
    dest:   "{{ ansible_user_dir }}/.config/alacritty.yml"

### Graphical environment Themes ###

# N/A to Mac

### yabai & skhd ###

# NB : we're not setting up the scripting addition because :
# * it requires disabling SIP, which is not advisable security-wise
# * it doesn't support M1 Macs anyway

- name: Create yabai config directory
  file:
    state:  directory
    dest:   "{{ ansible_user_dir }}/.config/yabai"

- name: Create yabairc
  copy:
    src:  "yabairc"
    dest: "{{ ansible_user_dir }}/.config/yabai/yabairc"
    mode: 0755

- name: Create skhd config directory
  file:
    state:  directory
    dest:   "{{ ansible_user_dir }}/.config/skhd"

- name: Configure skhdrc
  copy:
    src:  "skhdrc"
    dest: "{{ ansible_user_dir }}/.config/skhd/skhdrc"

- name: Create karabiner config directory
  file:
    state:  directory
    dest:   "{{ ansible_user_dir }}/.config/karabiner"

- name: Configure karabiner.json
  copy:
    src:  "karabiner.json"
    dest: "{{ ansible_user_dir }}/.config/karabiner/karabiner.json"

