### Package manager ###

  # NB : since the desktop/server distinction doesn't make sense for a mac, we install all packages here, and none in packages.yml
  # TODO : Install brew
- name: Install usual tools (Darwin)
  homebrew:
    name:
      - md5sha1sum # for command md5sum
      - exa
      - prettyping
    state: present

### Keyboard layouts ###

# TODO : install querty-lafayette here

### Alacritty ###

- name: Load alacritty config via .config/alacritty.yml
  file:
    state:  link
    follow: false
    src:    "{{ remote_directory }}/files/alacritty.yml"
    dest:   "{{ ansible_user_dir }}/.config/alacritty.yml"

### Graphical environment Themes ###

# N/A to Mac

### sway ###

# TODO : find some tiling window manager and set it up
