### Fonts ###

# TODO : remove, eventually
- name: Cleanup old font directories
  file:
    path:   "{{ item }}"
    state:  absent
  loop:
    - "{{ remote_directory }}/font_archives"
    - "{{ remote_directory }}/fonts"

# NB : We'd prefer this to be a symlink to a directory in .globalrc, but MacOS doesn't follow such symlinks
- name: Create custom fonts directory
  file:
    state:  directory
    path:   "{{ fonts_install_path }}"

# Recommended fonts for powerlevel10k
# NB : With this setup, we don't re-download the files unless the hardcoded hashes are changed.
# This means that if the files change, we'll only notice it on a fresh install (it will error until the hashes are fixed),
# but once the hashes are fixed, all machines will pick the change at their next deploy.
# The font files are expected to basically never change, so this should be alright
- name: Download MelsoLGS fonts
  get_url:
    dest:     "{{ fonts_install_path }}/{{ item.name }}"
    url:      "{{ item.url }}"
    checksum: "sha1:{{ item.sha1 }}"
    mode:     "0644"
  notify: Regenerate font cache
  loop:
    - name: "MesloLGS NF Regular.ttf"
      url:  "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
      sha1: "7c66a6d9a3a8d45a5b1fd9438899e4bdb3fbcc4d"
    - name: "MesloLGS NF Bold.ttf"
      url:  "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
      sha1: "fc5c6b09bbee77414cff0382f0942ec8bd0dec7e"
    - name: "MesloLGS NF Italic.ttf"
      url:  "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
      sha1: "1c60952c33e795a554e78f4099e9fcff29c8f14e"
    - name: "MesloLGS NF Bold Italic.ttf"
      url:  "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
      sha1: "c471873a8f31c67fa652a6c4bd58b3b045ce57a1"
  tags: online
