### Package manager ###

# Not much to be done here, the distinction between desktop and server doesn't make sense for a mac, and we already install what we need in "packages.yml"

### Keyboard layouts ###

# TODO : install querty-lafayette here

### Fonts ###

- name: Download MelsoLGS fonts
  get_url:
    dest:     "{{ ansible_user_dir }}/Library/Fonts/{{ item.name }}"
    url:      "{{ item.url }}"
    checksum: "sha1:{{ item.sha1 }}"
    mode:     "0644"
  loop: "{{ fonts }}"

### Alacritty ###

- name: Load alacritty config via .config/alacritty.yml
  file:
    state:  link
    follow: false
    src:    "{{ remote_directory }}/files/alacritty.yml"
    dest:   "{{ ansible_user_dir }}/.config/alacritty.yml"

### Graphical environment Themes ###

# N/A to Mac

### sway ###

# TODO : find some tiling window manager and set it up
