  # This is a bit of a hack
  #
  # We have several machines in the inventory on which we're supposed to only
  # ever deploy locally. Instead of always having to use --limit, or make some
  # complicated setup with groups, or use different inventories (etc), we start
  # with all of them, and fail it if the hostname doesn't match.
  #
  # It's a bit ugly, but far less error-prone and more convenient than relying on some
  # manual/local configuration
- name: Check ansible_hostname
  debug: "var=ansible_hostname"
  failed_when: true
  when: expected_hostname is defined and expected_hostname != ansible_hostname
  tags: always

- name: Check that we can actually become root
  command: "true"
  become: true
  changed_when: false
  when: have_root | bool

# Tombstones, TODO :remove at some point
- name: "TOMBSTONE : clear old blockinfiles"
  blockinfile:
    state: absent
    path: "{{ item }}"
    marker: "# {mark} GLOBALRC ANSIBLE MANAGED BLOCK"
  loop:
    - "{{ ansible_user_dir }}/.gitconfig"

- name: Create main directory
  file:
    path:   "{{ remote_directory }}"
    state:  directory

- name: Synchronize static files
  synchronize:
    src:        .
    dest:       "{{ remote_directory }}/files"
    recursive:  true
    delete:     true
    perms:      true
  tags: always

- name: Create templates directory
  file:
    state:  directory
    dest:   "{{ remote_directory }}/templates"

- name: Process templates going into "templates" directory
  template:
    src:  "{{ item }}"
    dest: "{{ remote_directory }}/templates/{{ item }}"
  tags: always
  with_items:
    - bazshrc.sh
    - inputrc
    - ssh_config
    - sshrc
    - tmux.conf

- name: Create the local_bin directory
  file:
    state: directory
    dest: "{{ remote_directory }}/local_bin"

# # NB: Nothing is done to remove executables added by previous versions or by the user
# - name: Download programs in local_bin directory
#   get_url:
#     url:  "{{ item }}"
#     dest: "{{ remote_directory }}/local_bin/"
#     mode: 0755
#   with_items:
#     - https://path/to/some/bin

- name: TOMBSTONE - remove previously manually downloaded difftastic
  file:
    path: "{{ remote_directory }}/local_bin/difft"
    state: absent

# TODO : cleanup task, remove eventually
- name: Remove manually-installed prettyping
  file:
    path: "{{ remote_directory }}/local_bin/prettyping"
    state: absent

- name: Setup the loading via .bashrc
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.bashrc"
    create: true
    marker: "# {mark} GLOBALRC ANSIBLE MANAGED BLOCK"
    block:  |
      # Load custom configuration
      . {{ remote_directory }}/files/bashrc

- name: Install packages
  import_tasks:  packages.yml

- name: Set zsh as default shell
  user:
    name:   "{{ ansible_user_id }}"
    shell:  /bin/zsh
  become:   true
  when:     have_root | bool

  # TODO : Do this with an include
- name: Load IRB configuration
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.irbrc"
    create: true
    marker: "# {mark} GLOBALRC ANSIBLE MANAGED BLOCK"
    block:  |
      IRB.conf[:SAVE_HISTORY] = 200
      IRB.conf[:HISTORY_FILE] = '~/.irb-history'

- name: Install desktop-specific stuff (common)
  import_tasks: desktop_common.yml
  when: (desktop_linux | bool) or ansible_system == "Darwin"
  tags: desktop

- name: Install desktop-specific stuff (linux)
  import_tasks: desktop_linux.yml
  when: desktop_linux | bool
  tags: desktop

- name: Install desktop-specific stuff (Mac)
  import_tasks: desktop_mac.yml
  when: ansible_system == "Darwin"
  tags: desktop

- name: Install zsh configuration
  import_tasks: zsh.yml
  tags: zsh

- name: Install vim configuration
  import_tasks: vim.yml
  tags: vim

- name: Install ssh configuration
  import_tasks: ssh.yml
  tags: ssh

- name: Install tmux configuration
  import_tasks: tmux.yml
  tags: tmux

- name: Load screen configuration
  blockinfile:
    dest:         "{{ ansible_user_dir }}/.screenrc"
    insertbefore: BOF
    create:       true
    marker:       "# {mark} GLOBALRC ANSIBLE MANAGED BLOCK"
    block:  |
      # Loading global screen configuration
      source {{ remote_directory }}/files/screenrc

# Mass-renaming tool with vim
- name: Download vimv
  get_url:
    url:  https://raw.githubusercontent.com/thameera/vimv/master/vimv
    dest: "{{ remote_directory }}/"
    mode: 0755
  tags: online
