  # This is a bit of a hack
  #
  # We have several machines in the inventory on which we're supposed to only
  # ever deploy locally. Instead of always having to use --limit, or make some
  # complicated setup with groups, or use different inventories (etc), we start
  # with all of them, and fail it if the hostname doesn't match.
  #
  # It's a bit ugly, but far less error-prone and more convenient than relying on some
  # manual/local configuration
- name: Check ansible_hostname
  debug: "var=ansible_hostname"
  failed_when: true
  when: expected_hostname is defined and expected_hostname != ansible_hostname
  tags: always

- name: Check that we can actually become root
  command: "true"
  become: true
  changed_when: false
  when: have_root | bool

- name: Create main directory
  file:
    path:   "{{ remote_directory }}"
    state:  directory

- name: Synchronize static files
  synchronize:
    src:        .
    dest:       "{{ remote_directory }}/files"
    recursive:  true
    delete:     true
    perms:      true
    rsync_opts:
      - "--exclude=*.swp" # vim tempfiles
  tags: always

- name: Create templates directory
  file:
    state:  directory
    dest:   '{{ remote_directory }}/templates'

- name: Create templates directory structure
  file:
    state: directory
    dest: '{{ remote_directory }}/templates/{{ item.path }}'
  with_filetree: '../templates'
  when: item.state == 'directory'

# TODO : This section is to remove, we're going to process templates separately
- name: Process templates
  template:
    src: '{{ item.src }}'
    dest: '{{ remote_directory }}/templates/{{ item.path }}'
  with_filetree: '../templates'
  when: item.state == 'file' and not (item.path | regex_search('.swp'))
  tags: always

- name: Create the local_bin directory
  file:
    state: directory
    dest: '{{ remote_directory }}/local_bin'

# NB: Nothing is done to remove executables added by previous versions or by the user
- name: Download programs in local_bin directory
  get_url:
    url:  "{{ item }}"
    dest: "{{ remote_directory }}/local_bin/"
    mode: 0755
  with_items:
    - https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping

# Cleanup previous manual exa install
# TODO : remove, enventually
- name: Remove exa directory
  file:
    state: absent
    dest: "{{ remote_directory }}/exa"
  when: ansible_os_family == "RedHat"

- name: Remove exa binary
  file:
    state: absent
    dest: "{{ remote_directory }}/local_bin/exa"
  when: ansible_os_family == "RedHat"

- name: Create exa directory
  file:
    state: directory
    dest: "{{ remote_directory }}/exa"
  when: ansible_os_family == "Debian"

  # NB : exa is only packaged since debian 10 (buster) and ubuntu 19.04
  # Waiting for ubuntu 20.04
- name: Download and extract exa
  unarchive:
    # NB : There is no deb package for exa, nor any permalink to the latest version
    src: https://github.com/ogham/exa/releases/download/v0.8.0/exa-linux-x86_64-0.8.0.zip
    dest: "{{ remote_directory }}/exa/"
    remote_src: true
  when: ansible_os_family == 'Debian'

- name: Copy exa binary
  copy:
    src: "{{ remote_directory }}/exa/exa-linux-x86_64"
    dest: "{{ remote_directory }}/local_bin/exa"
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Setup the loading via .bashrc
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.bashrc"
    create: true
    block:  |
      # Load custom configuration
      . {{ remote_directory }}/files/bashrc

- name: Start the components requiring root access
  import_tasks:  root.yml
  become:   true
  when:     have_root | bool

  # TODO : Do this with an include
- name: Load IRB configuration
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.irbrc"
    create: true
    block:  |
      IRB.conf[:SAVE_HISTORY] = 200
      IRB.conf[:HISTORY_FILE] = '~/.irb-history'

- name: Load git configuration
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.gitconfig"
    create: true
    block:  |
      # Loading global git configuration
      [include]
        path = {{ remote_directory }}/templates/gitconfig
      # Global .gitignore
      [core]
        excludesfile = {{ remote_directory }}/files/gitignore

- name: Install various x configurations
  import_tasks: desktop.yml
  when: desktop | bool
  tags: desktop

- name: Install zsh configuration
  import_tasks: zsh.yml
  tags: zsh

- name: Install vim configuration
  import_tasks: vim.yml
  tags: vim

- name: Install ssh configuration
  import_tasks: ssh.yml
  tags: ssh

- name: Install tmux configuration
  import_tasks: tmux.yml
  tags: tmux

- name: Load screen configuration
  blockinfile:
    dest:         "{{ ansible_user_dir }}/.screenrc"
    insertbefore: BOF
    create:       true
    block:  |
      # Loading global screen configuration
      source {{ remote_directory }}/files/screenrc

# Mass-renaming tool with vim
- name: Download vimv
  get_url:
    url:  https://raw.githubusercontent.com/thameera/vimv/master/vimv
    dest: "{{ remote_directory }}/"
    mode: 0755

- name: Cleanup old configs
  import_tasks: cleanup.yml
  tags: tmux

