- name: Create main directory
  file:
    path:   "{{ remote_directory }}"
    state:  directory

- name: Synchronize static files
  synchronize:
    src:        .
    dest:       "{{ remote_directory }}/files"
    recursive:  true
    delete:     true
    perms:      true

- name: Create templates directory
  file:
    state:  directory
    dest:   '{{ remote_directory }}/templates'

- name: Create templates directory structure
  file:
    state: directory
    dest: '{{ remote_directory }}/templates/{{ item.path }}'
  with_filetree: '../templates'
  when: item.state == 'directory'

# TODO : This section is to remove, we're going to process templates separately
- name: Process templates
  template:
    src: '{{ item.src }}'
    dest: '{{ remote_directory }}/templates/{{ item.path }}'
  with_filetree: '../templates'
  when: item.state == 'file'

- name: Setup the loading via .bashrc
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.bashrc"
    create: true
    block:  |
      # Load custom configuration
      . {{ remote_directory }}/files/bash/bashrc

- name: Start the components requiring root access
  include:  root.yml
  become:   true
  when:     have_root

- name: Load IRB configuration
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.irbrc"
    create: true
    block:  |
      IRB.conf[:SAVE_HISTORY] = 200
      IRB.conf[:HISTORY_FILE] = '~/.irb-history'

- name: Load git configuration
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.gitconfig"
    create: true
    block:  |
      # Loading global git configuration
      [include]
        path = {{ remote_directory }}/files/gitconfig
      # Global .gitignore
      [core]
        excludesfile = {{ remote_directory }}/files/gitignore

- name: Install zsh configuration
  include: zsh.yml
  tags: zsh

- name: Install vim configuration
  include: vim.yml
  tags: vim

# /!\ TODO: Find a way allowing local configuration
# Currently, this task will fail if there is already a file
- name: Install tmux configuration
  file:
    path:   "{{ ansible_user_dir }}/.tmux.conf"
    src:    "{{ remote_directory }}/files/tmux.conf"
    state:  link
