
- name: Install zsh and usual tools (Debian)
  apt:
    update_cache:     true
    cache_valid_time: 3600
    name:
      - zsh
      - git
      - vim
      - tmux
      - most
      - curl
      - eza
      - git-delta

      # Language-specific package managers and tooling
      - cargo         # rust deps with cargo

  when: have_root and ansible_os_family == 'Debian'

# RELEASE_BLOCKER move macos packages install here

- name: Install (compile) rust programs with cargo
  community.general.cargo:
    name:
      # There's a deb package downloadable from the github releases
      # There is no RPM yet (https://github.com/ellie/atuin/issues/990)
      # As of 2024-06-12, v18.3 does not compile, pin it for now.
      - atuin
    state: present
    version: "18.2.0"
  when: ansible_system != "Darwin"  # Installed with brew on macOS
