
- name: Set zsh as default shell
  user:
    name:   "{{ ansible_user_id }}"
    shell:  /bin/zsh

- name: Install zsh and usual tools (Debian)
  apt:
    update_cache:     true
    cache_valid_time: 3600
    name:
      - zsh
      - git
      # TODO: If we're on a desktop, install vim with clipboard support (vim-gui-common)
      - vim
      - screen
      - tmux
      - most
      - mosh
  when: ansible_os_family == 'Debian'
