- name: Create .ssh directory
  file:
    path:   "{{ ansible_user_dir }}/.ssh"
    state:  directory

- name: Load ssh configuration
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.ssh/config"
    create: yes
    marker: "# {mark} GLOBALRC ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    block:  |
      # Loading global ssh configuration
      Host *
        Include {{ remote_directory }}/templates/ssh_config
