- name: Create .ssh directory
  file:
    path:   "{{ ansible_user_dir }}/.ssh"
    state:  directory

- name: Load ssh configuration
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.ssh/config"
    create: yes
    insertbefore: BOF
    block:  |
      # Loading global ssh configuration
      Include {{ remote_directory }}/files/ssh_config

- name: Clone sshrc
  git:
    repo:   https://github.com/Russell91/sshrc
    dest:   "{{ remote_directory }}/sshrc"
    depth:  1

