- name: Create .ssh directory
  file:
    path:   "{{ ansible_user_dir }}/.ssh"
    state:  directory

- name: Load ssh configuration
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.ssh/config"
    create: yes
    insertbefore: BOF
    block:  |
      # Loading global ssh configuration
      Include {{ remote_directory }}/templates/ssh_config

- name: Clone sshrc
  git:
    # The original repo (and user) are gone :/
    # repo:     https://github.com/Russell91/sshrc
    repo:     https://github.com/toadjaune/sshrc
    dest:     "{{ remote_directory }}/sshrc"
    version:  0.6.2
    depth:    1

