
- name: Load tmux configuration
  blockinfile:
    dest:         "{{ ansible_user_dir }}/.tmux.conf"
    insertbefore: BOF
    create:       true
    marker:       "# {mark} GLOBALRC ANSIBLE MANAGED BLOCK"
    block:  |
      # Loading global tmux configuration
      source-file {{ remote_directory }}/templates/tmux.conf

