
- name: Load tmux configuration
  blockinfile:
    dest:         "{{ ansible_user_dir }}/.tmux.conf"
    insertbefore: BOF
    create:       true
    block:  |
      # Loading global tmux configuration
      source-file {{ remote_directory }}/files/tmux.conf

