- name: Create vim directory
  file:
    state:  directory
    dest: '{{ remote_directory }}/vim'

- name: Generate main vimrc
  template:
    src:  vimrc
    dest: '{{ remote_directory }}/vim/'

- name: Setup Vim configuration loading
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.vimrc"
    create: true
    marker: "\" {mark} ANSIBLE MANAGED BLOCK"
    block:  |
      " Loading global vim configuration
      source {{ remote_directory }}/vim/vimrc

- name: Install Vundle for Vim plugin management
  git:
    repo:   https://github.com/VundleVim/Vundle.vim.git
    dest:   "{{ remote_directory }}/vim/bundle/Vundle.vim"
    update: true
  tags: vundle

- name: Use Vundle to Install/Update vim plugins
  command:      vim +PluginInstall! +qall
  # NB : We have no way to know if this commad actually changed something
  changed_when: false
  tags: vundle

- name: Download powerline modified fonts for vim-airline
  git:
    repo:   https://github.com/powerline/fonts
    dest:   "{{ remote_directory }}/powerline-fonts"
    update: true

# NB: you still have to reconfigure your terminal to use these fonts
# TODO : Mention it in README ?
- name: Install powerline modified fonts for airline
  command: './install.sh'
  args:
    chdir: "{{ remote_directory }}/powerline-fonts"
  changed_when: false

