- name: Create vim directory
  file:
    state:  directory
    dest: '{{ remote_directory }}/vim'

- name: Generate main vimrc
  template:
    src:  vimrc
    dest: '{{ remote_directory }}/vim/'

- name: Setup Vim configuration loading
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.vimrc"
    create: true
    marker: "\" {mark} GLOBALRC ANSIBLE MANAGED BLOCK"
    block:  |
      " Loading global vim configuration
      source {{ remote_directory }}/vim/vimrc

- name: Create colorschemes-manual directory
  file:
    path:   "{{ remote_directory }}/vim/bundle/colorschemes-manual/colors"
    state:  directory

- name: Download manually managed colorschemes
  get_url:
    url:  "{{ item }}"
    dest: "{{ remote_directory }}/vim/bundle/colorschemes-manual/colors"
  tags: online
  with_items:
    - https://raw.githubusercontent.com/garybernhardt/dotfiles/master/.vim/colors/grb256.vim
    # - https://github.com/ryanb/dotfiles/raw/master/vim/colors/railscasts.vim # broken as of 2023-12-03

- name: Install vim-plug for Vim plugin management
  git:
    repo:   https://github.com/junegunn/vim-plug
    dest:   "{{ remote_directory }}/vim/bundle/vim-plug"
    depth:  1
  tags: vimplug

# NB : This is normally not doing anything
# It is useful for example when changing the upstream URL of a repo
- name: Use vim-plug to Clean invalid vim plugins
  command:  vim +PlugUpdate +qall
  # NB : We have no way to know if this command actually changed something
  changed_when: false
  tags:
    - vimplug
    - online

- name: Use vim-plug to Install/Update vim plugins
  command:  vim +PlugUpdate +qall
  # NB : We have no way to know if this command actually changed something
  changed_when: false
  tags:
    - vimplug
    - online

