### Fonts ###

- name: Create font directories
  file:
    state:  directory
    dest: '{{ remote_directory }}/{{ item }}'
  loop:
    - font_archives
    - fonts

# TODO : Mention it in README ?
# These fonts are required by :
# - vim-airline
# - vim-devicons
# - vim-nerdtree-syntax-highlight
- name: Download/extract extra fonts
  include_tasks: font.yml
  loop_control:
    loop_var: font_url
  loop:
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/UbuntuMono.zip
  notify: Regenerate font cache

- name: Install fonts (by symlinking)
  file:
    state:  link
    src:    "{{ remote_directory }}/fonts/"
    dest:   "{{ ansible_user_dir }}/.local/share/fonts/globalrc_fonts"

  # This is not strictly necessary, but we prefer changing configuration requiring specific fonts only once they are installed
  # If this ever causes issues with another handler, change it to a conditional task
- meta: flush_handlers

### Alacritty ###

- name: Create alacritty directory
  file:
    state:  directory
    dest: '{{ remote_directory }}/alacritty'

- name: Download alacritty archive
  get_url:
    url:  "https://github.com/jwilm/alacritty/releases/download/binaries/Alacritty-x86_64.tar.gz"
    dest: "{{ remote_directory }}/alacritty/archive.tar.gz"

- name: Extract alacritty archive
  unarchive:
    src:  "{{ remote_directory }}/alacritty/archive.tar.gz"
    dest: "{{ remote_directory }}/alacritty/"
    remote_src: yes

- name: Copy alactritty executable to /usr/local/bin
  copy:
    src:  "{{ remote_directory }}/alacritty/alacritty"
    dest: "/usr/local/bin/alacritty"
    owner: root
    group: root
    mode:  0755
  become: true
  when: have_root

- name: Load alacritty config via .config/alacritty.yml
  file:
    state:  link
    follow: false
    src:    "{{ remote_directory }}/files/alacritty.yml"
    dest:   "{{ ansible_user_dir }}/.config/alacritty.yml"

- name: Install xclip (Debian)
  apt:
    cache_valid_time: 86400 # 1 day
    name:
      - xclip
  become: true
  when: have_root and ansible_os_family == "Debian"

- name: Install xclip (RedHat)
  dnf:
    name:
      - xclip
  become: true
  when: have_root and ansible_os_family == "RedHat"

### Graphical environment Themes ###

# See : https://www.reddit.com/r/archlinux/comments/2eo3qq/is_it_possible_to_get_qt_to_properly_use_gtk/
# See : https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#Using_a_GTK.2B_icon_theme_in_Qt_apps
# The solution chosen here for consistent look between Qt and GTK applications is to use a same theme implemented
# in both native formats

- name: Load GTK2 configuration via .gtkrc-2.0
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.gtkrc-2.0"
    create: true
    block:  |
      # Load GTK2 configuration
      include "{{ remote_directory }}/files/gtkrc-2.0"

# /!\ This is a destructive operation /!\
# It does not seem possible to make an include in gtk3 config
# https://superuser.com/q/1370777/733026
- name: Load GTK3 configuration via .config/gtk-3.0/settings.ini
  file:
    dest:   "{{ ansible_user_dir }}/.config/gtk-3.0/settings.ini"
    src:    "{{ remote_directory }}/files/gtk-3.0-settings.ini"
    state:  link
    force:  true

# This is a Qt5-native port of GTK Adwaita theme
# TODO : check it also works for Qt4 (or add adwaita-qt4)
- name: Install adwaita-qt (Debian)
  apt:
    cache_valid_time: 86400 # 1 day
    name:
      - adwaita-qt
  become: true
  when: have_root and ansible_os_family == "Debian"

- name: Install adwaita-qt (RedHat)
  dnf:
    name:
      - adwaita-qt
  become: true
  when: have_root and ansible_os_family == "RedHat"

# NB : Qt5 theme is loaded through QT_STYLE_OVERRIDE env variable
- name: Load Qt4 graphical configuration via .config/Trolltech.conf
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.config/Trolltech.conf"
    create: true
    block:  |
      # Set Qt4 Theme
      [Qt]
      style=Adwaita-Dark

- name: Load .profile
  blockinfile:
    dest:         "{{ ansible_user_dir }}/.profile"
    insertbefore: BOF
    create:       true
    block:  |
      # Loading global .profile
      source {{ remote_directory }}/files/profile

### i3 ###

- name: Install i3-related packages (Debian)
  apt:
    cache_valid_time: 86400 # 1 day
    name:
      - i3
      # Display desktop background image
      - feh
  become: true
  when: have_root and ansible_os_family == "Debian"

- name: Install i3-related packages (RedHat)
  dnf:
    name:
      - i3
      - feh
      # nmtui is a terminal graphical interface to NetworkManager
      # TODO : Find the equivalent debian package
      - NetworkManager-tui
  become: true
  when: have_root and ansible_os_family == "RedHat"


- name: Create i3 config directory
  file:
    state:  directory
    dest:   "{{ ansible_user_dir }}/.config/i3"

- name: Install i3 config (by symlinking)
  file:
    state:  link
    follow: false
    src:    "{{ remote_directory }}/files/i3_config"
    dest:   "{{ ansible_user_dir }}/.config/i3/config"

### Other ###

- name: Load urxvt configuration via .Xresources
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.Xresources"
    create: true
    marker: "! {mark} ANSIBLE MANAGED BLOCK"
    block:  |
      ! Load urxvt configuration
      #include "{{ remote_directory }}/files/urxvt.conf"
