# TODO : load this file only if zsh is installed ?

- name: Create zsh_plugins directory
  file:
    path:   "{{ remote_directory }}/zsh_plugins"
    state:  directory

- name: Clone zsh plugins
  git:
    repo:     "{{ item.repo }}"
    dest:     "{{ remote_directory }}/zsh_plugins/{{ item.name }}"
    version:  "{{ item.version }}"
    depth:    1
  tags: online
  with_items:
    - name:     powerlevel10k
      repo:     https://github.com/romkatv/powerlevel10k
      version:  v1.14.6

    - name:     zsh-autosuggestions
      repo:     https://github.com/zsh-users/zsh-autosuggestions
      version:  v0.6.4

    - name:     zsh-syntax-highlighting
      repo:     https://github.com/zsh-users/zsh-syntax-highlighting
      version:  0.7.1

    - name:     zsh-completions
      repo:     https://github.com/zsh-users/zsh-completions
      version:  master

# Some specific tasks need to be done before loading .zshrc
# https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout#71258
# http://zsh.sourceforge.net/Intro/intro_3.html
# Currently, we need it only to run code before loading /etc/zsh/zshrc
- name: Setup early configuration via .zshenv
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.zshenv"
    create: true
    block:  |
      # Disable compinit call in /etc/zsh/zshrc on ubuntu
      skip_global_compinit=1

- name: Setup the loading via .zshrc
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.zshrc"
    create: true
    block:  |
      # Load custom configuration
      . {{ remote_directory }}/files/zshrc
