# TODO : load this file only if zsh is installed ?

- name: Clone zplug
  git:
    repo:   'https://github.com/toadjaune/zplug.git'
    dest:   "{{ remote_directory }}/zplug"
    depth:  1

# TODO : See if we can install it in a cleaner way
# virtualenv ?
# --target ? https://stackoverflow.com/questions/2915471/install-a-python-package-into-a-different-directory-using-pip#19404371
# TODO : See if we need extra dependencies for perfs
# https://powerline.readthedocs.io/en/latest/installation.html
- name: Install powerline
  pip:
    name:       powerline-status
    state:      latest
    extra_args: --user

- name: Setup the loading via .zshrc
  blockinfile:
    dest:   "{{ ansible_user_dir }}/.zshrc"
    create: true
    block:  |
      # Load custom configuration
      . {{ remote_directory }}/files/zsh/zshrc

