  # NB : There's no need to do anything after adding fonts on MacOS
- name: Regenerate font cache
  command: "fc-cache -fv"
  changed_when: true
  when: ansible_system != 'Darwin'

  # NB : Only tested on Fedora
- name: Restart bluez
  systemd_service:
    name: bluetooth
    state: restarted
  become: true

