
  # I couldn't find a way to make ansible regenerate initramfs with the new keyboard layout
  # I tried :
  # * Restarting keyboard-setup daemon
  # * setupcon
  # * setxkbmap
- debug:
    msg: "WARNING : Reboot then run `update-initramfs -u`"
  listen: keyboard_config
  changed_when: true
  when: ansible_os_family == "Debian"

- name: Regenerate initramfs (Fedora)
  command: "dracut --force"
  become: true
  listen: keyboard_config
  changed_when: true
  when: ansible_os_family == "RedHat"

- name: Reload sway config
  command: "swaymsg reload"
  changed_when: true

- name: Reload kanshi config
  command: "kanshictl reload"
  changed_when: true

  # NB : There's no need to do anything after adding fonts on MacOS
- name: Regenerate font cache
  command: "fc-cache -fv"
  changed_when: true
  when: ansible_system != 'Darwin'

  # NB : Only tested on Fedora
- name: Restart bluez
  systemd:
    name: bluetooth
    state: restarted
  become: true

