# Options documentation : https://github.com/alacritty/alacritty/blob/master/alacritty.yml

# Requires :
# xclip for copy-paste shortcuts (optional)

env:
  # This variable is set directly by the terminal, so that we can have different behaviour
  # depending on the terminal emulator
  GLOBALRC_PATCHED_FONT: "1"

# Enable on i3
#window:
#  decorations: none

font:
  normal:
    family: "UbuntuMono Nerd Font Mono"
  bold:
    family: "UbuntuMono Nerd Font Mono"
    style:  Bold
  italic:
    family: "UbuntuMono Nerd Font Mono"
    style:  Italic
  size: 12

# Disable live relaoading because :
# - It's not really useful in my config modification workflow
# - I'm actually happy not to ruin the shell I'm changing the config from while I'm doing it
live_config_reload: false

colors:
  primary:
    background: '0x000000'
    foreground: '0xeaeaea'
key_bindings:
  # Consistently delete last word with Ctrl-Backspace
  # This is a standard across graphical apps, but terminal apps usually do it with Ctrl-W (Emacs bindings)
  # It at least works with vim, zsh (with my zle config), readline (with my config) (includes bash)
  # Should also work out of the box with these programs since my config pays attention to keep most emacs bindings when switching to vi mode
  # NB : This is the actual Ctrl-W character, not an escape sequence
  - { key: Back, mods: Control, chars: "" }

