# Config documentation : https://alacritty.org/config-alacritty.html

# Requires :
# xclip for copy-paste shortcuts (optional)


# Disable live reloading because :
# - It's not really useful in my config modification workflow
# - I'm actually happy not to ruin the shell I'm changing the config from while I'm doing it
live_config_reload = false

[window]
decorations = "none"
opacity = 0.7

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[colors.bright]
black   = "0x666666"
blue    = "0x7aa6da"
cyan    = "0x54ced6"
green   = "0x9ec400"
magenta = "0xb77ee0"
red     = "0xff3334"
white   = "0xffffff"
yellow  = "0xe7c547"

[colors.dim]
black   = "0x333333"
blue    = "0x6699cc"
cyan    = "0x66cccc"
green   = "0x99cc99"
magenta = "0xcc99cc"
red     = "0xf2777a"
white   = "0xdddddd"
yellow  = "0xffcc66"

[colors.normal]
black   = "0x000000"
blue    = "0x7aa6da"
cyan    = "0x70c0ba"
green   = "0xb9ca4a"
magenta = "0xc397d8"
red     = "0xd54e53"
white   = "0xffffff"
yellow  = "0xe6c547"

[env]
# This variable is set directly by the terminal, so that we can have different behaviour
# depending on the terminal emulator
GLOBALRC_PATCHED_FONT = "1"

[font]
size = 12
[font.normal]
family = "MesloLGS NF"

# Consistently delete last word with Ctrl-Backspace
# This is a standard across graphical apps, but terminal apps usually do it with Ctrl-W (Emacs bindings)
# It at least works with vim, zsh (with my zle config), readline (with my config) (includes bash)
# Should also work out of the box with these programs since my config pays attention to keep most emacs bindings when switching to vi mode
[[keyboard.bindings]]
chars = "\u0017" # Ctrl-W
key = "Back"
mods = "Control"

# This is an ugly workaround for MacOS
# cf https://github.com/alacritty/alacritty/issues/5755
# Basically, the Alt layer is fucked up, and alacritty sends Alt+char instead of char
# We hardcode here the parts of the Alt layer that we use as a workaround
# NB : I'm not sure if this is ignored on Linux or if it's interpreted as Alt, but either way, it doesn't seem to break anything, so...
[[keyboard.bindings]]
chars = "<"
key = 13
mods = "Option"
[[keyboard.bindings]]
chars = ">"
key = 14
mods = "Option"
[[keyboard.bindings]]
chars = "{"
key = 0
mods = "Option"
[[keyboard.bindings]]
chars = "["
key = 1
mods = "Option"
[[keyboard.bindings]]
chars = "]"
key = 2
mods = "Option"
[[keyboard.bindings]]
chars = "}"
key = 3
mods = "Option"

