# Location of the main directory on the remote machine
remote_directory:   "{{ ansible_user_dir }}/.globalrc"

# Set this to true if you want to perform the operations requiring root, for a first-time install
have_root:  false

# Set this to true if the machine has no graphical interface. It skips useless steps.
server: false

# Movement keys (defaults are for bépo layout)
# Right hand
key_rh_left:  't'
key_rh_down:  's'
key_rh_up:    'r'
key_rh_right: 'n'

# Left hand
key_lh_left:  'a'
key_lh_down:  'u'
key_lh_up:    'i'
key_lh_right: 'e'

# Tmux configuration
tmux_status_bar_colour: 'colour2'
tmux_status_bar_inactive_colour: 'colour25'

# SSH Agent Forwarding socket symlink
ssh_auth_sock: '/tmp/ssh-auth-sock-$UID'
