# Location of the main directory on the remote machine
remote_directory:   "{{ ansible_user_dir }}/.globalrc"

# Set this to true if you want to perform the operations requiring root, for a first-time install
have_root:  false

# Set this to true if the machine has a graphical interface (X server, etc…). It skips useless steps.
desktop_linux: false

# add a custom wrapper in /usr/local/bin/ to start electron programs through native wayland
# NB : There is no check that the corresponding program is actually installed, so we may
# create a script showing up in PATH but doomed to fail
electron_wayland_to_wrap:
  - slack
  # Discord looks broken on native wayland
  # - Discord
  # spotify has a weird behavior, where it creates a second window via XWayland, empty
  # - spotify

# Movement keys
# Right hand
key_rh_left:  'h'
key_rh_down:  'j'
key_rh_up:    'k'
key_rh_right: 'l'

# Tmux configuration
tmux_status_bar_colour: 'colour2'
tmux_status_bar_inactive_colour: 'colour25'

# SSH Agent
ssh_agent_symlink_path: '/tmp/ssh-auth-sock-$UID'

# keyboard layout
keyboard_layout: 'fr'
keyboard_variant: 'lafayette'

# Git config
# NB : we let those undefined on purpose, we want them to be defined per host
# git_user_name: "Henri Golo"
# git_user_email: "henri.golo@example.com"

# Extra ssh config to be prepended to the global config
extra_ssh_config_host: ""
extra_ssh_config_global: ""

# Sway setup
# sway_output_primary: "" # Mandatory for graphical setup
sway_output_custom_1: "nop 'Mode not defined'"
sway_output_custom_2: "nop 'Mode not defined'"
# Those paths are relative to user home
sway_wallpaper_path:  ".config/sway/wallpaper.png"
sway_lockscreen_path: ".config/sway/lockscreen.png"

# On both OS, we can just dump ttf files in a directory, only the path changes
fonts_install_path: "{{ ansible_user_dir }}/{{ (ansible_system == 'Darwin') | ternary ('Library/Fonts', '.local/share/fonts') }}/globalrc_fonts"

# Firefox default profile
firefox_profile_name: default-release
