# Location of the main directory on the remote machine
remote_directory:   "{{ ansible_user_dir }}/.globalrc"
# Userspace programming language version managers
volta_home:               "{{ ansible_user_dir }}/.volta"     # default value
# Userspace language-specific install paths
userspace_bin_path_cargo: "{{ ansible_user_dir }}/.cargo/bin" # default value
userspace_bin_path_go:    "{{ ansible_user_dir }}/go/bin"     # default value

# Set this to true if you want to perform the operations requiring root, for a first-time install
have_root:  false

# Set this to true if the machine has a graphical interface (X server, etc…). It skips useless steps.
# RELEASE_BLOCKER switch to just desktop (and then include macos) or remove completely
desktop_linux: true

# SSH Agent
ssh_agent_symlink_path: '/tmp/ssh-auth-sock-$UID'

# keyboard layout
keyboard_layout: 'fr'

# On both OS, we can just dump ttf files in a directory, only the path changes
fonts_install_path: "{{ ansible_user_dir }}/{{ (ansible_system == 'Darwin') | ternary ('Library/Fonts', '.local/share/fonts') }}/globalrc_fonts"

# Firefox default profile
firefox_profile_name: default-release

# RELEASE_BLOCKER support azerty/qwerty
